{% set name = "p4est" %}
{% set version = "2.8.5.5-9ddbb" %}
{% set sha256 = "1a1fd146c07b8b4de369d2ac63984533e33e576c89d1f7bab9a15b343a6e403a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://{{ name }}.github.io/release/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  script: build.sh  # [not win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
  run:

test:
  imports:
  requires:
  commands:
    - make -j3 distcheck

about:
  home: http://www.p4est.org/
  summary: 'The "p4est" forest-of-octrees library'
  description: |
    `p4est` is a C library to manage a collection (a forest) of multiple
    connected adaptive quadtrees or octrees in parallel.
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  doc_url: https://p4est.github.io/api/p4est-latest/index.html
  dev_url: https://github.com/cburstedde/p4est

extra:
  recipe-maintainers:
    - ?
